import 'package:flutter/material.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:shared_preferences/shared_preferences.dart';

part 'localization_provider.g.dart';

/// Traduzioni per la lingua corrente.
///
/// Immutabile: cambiare lingua produce una nuova istanza, non muta questa.
@immutable
class Localization {
  const Localization(this.locale);

  final Locale locale;

  /// Traduce [key]. Se manca nel dizionario restituisce la chiave stessa,
  /// cosi la stringa non tradotta e visibile invece di sparire.
  String t(String key) {
    final table = locale.languageCode == 'it' ? _it : _en;
    return table[key] ?? key;
  }

  static final Map<String, String> _en = {
    'settings_title': 'Settings',
    'account_section': 'ACCOUNT',
    'my_profile': 'My Profile',
    'body_measurements': 'Body Measurements',
    'subscription': 'Subscription',
    'gym_settings_section': 'GYM SETTINGS',
    'gym_details': 'Gym Details',
    'gym_location': 'Gym Location',
    'integrations_section': 'INTEGRATIONS',
    'preferences_section': 'PREFERENCES',
    'notifications': 'Notifications',
    'app_theme': 'App Theme',
    'language': 'Language',
    'primary_color': 'Primary Color',
    'load_default_data': 'Load Default Data',
    'sign_out': 'Sign Out',
    'guest_user': 'Guest User',
    'track_progress': 'Track your progress',
    'free_plan': 'Free Plan',
    'expires': 'Expires',
    'set_name_address': 'Set Name & Address',
    'location_pinned': 'Location pinned',
    'tap_to_set': 'Tap to set location',
    'sync_steps': 'Sync steps, calories, and more',
    'permissions_granted': 'Permissions granted!',
    'default_loaded': 'Default exercises loaded!',
    'gym_info_saved': 'Gym Info Saved!',
    'system': 'System',
    'light': 'Light',
    'dark': 'Dark',
    'select_language': 'Select Language',
    'home': 'Home',
    'achievements': 'Achievements',
    'stopwatch_menu': 'Stopwatch',
    'connect_friend': 'Connect Friend',
    'stopwatch_tab': 'Stopwatch',
    'timer_tab': 'Timer',
    'lap': 'Lap',
    'reset': 'Reset',
    'pause': 'Pause',
    'start': 'Start',
    'tap_to_edit': 'Tap to edit',

    // Calendar
    'calendar_title': 'Calendar',
    'select_day': 'Select a day',
    'no_workouts_day': 'No workouts this day',
    'schedule_workout': 'Schedule Workout',
    'schedule_workout_btn': 'Schedule Workout',
    'delete_event_title': 'Delete Event?',
    'delete_event_body': 'This action cannot be undone.',
    'sync_calendar': 'Sync to Calendar',
    'workout_label': 'Workout:',
    'scheduled_using': 'Scheduled using GymFlow',
    'select_workout_schedule': 'Select Workout to Schedule',
    'no_workouts_found': 'No workouts found. Create one first!',

    // Connect Friend
    'connect_friends_title': 'Connect with Friends',
    'your_friend_code': 'Your Friend Code',
    'share_code_msg': 'Share this code with your friends so they can add you!',
    'enter_friend_code': 'Enter Friend Code',
    'friend_code_hint': 'e.g. A1B2C3',
    'connect_btn': 'CONNECT',
    'your_friends_list': 'Your Friends',
    'no_friends_msg': 'No friends yet. Add some!',
    'privacy_settings': 'Privacy:',
    'share_calendar': 'Share Calendar',
    'share_calendar_sub': 'Allow viewing your workout history',
    'share_programs': 'Share Programs',
    'share_programs_sub': 'Allow viewing/copying your programs',
    'done': 'DONE',
    'cant_add_self': "You can't add yourself!",
    'friend_connected': 'Friend connected successfully!',
    'friend_not_found': 'Friend not found with code:',

    // Program List
    'my_programs_title': 'My Programs',
    'no_programs_yet': 'No Programs Yet',
    'create_program_msg': 'Create a workout program (Scheda) to get started',
    'delete': 'Delete',
    'delete_program_title': 'Delete Program?',
    'delete_program_body_prefix': 'Are you sure you want to delete',
    'program_deleted': 'Program deleted',
    'active_caps': 'ACTIVE',
    'ongoing': 'Ongoing',
    'no_dates': 'No dates set',
    'days_label': 'Days',

    // Dashboard
    'dashboard_title': 'Dashboard',
    'overview_tab': 'Overview',
    'history_tab': 'History',
    'workouts_label': 'Workouts',
    'streak_label': 'Streak',
    'steps_label': 'Steps',
    'active_cal_label': 'Active Cal',
    'heart_rate_label': 'Heart Rate',
    'sleep_label': 'Sleep',
    'volume_label': 'Volume',
    'avg_intensity_label': 'Avg Intensity',
    'my_gym_label': 'My Gym',
    'workout_activity_chart': 'Workout Activity',
    'body_progress_chart': 'Body Progress',
    'workout_types_chart': 'Workout Types',
    'workout_type_strength': 'Strength',
    'workout_type_cardio': 'Cardio',
    'workout_type_hypertrophy': 'Hypertrophy',
    'workout_type_flexibility': 'Flexibility',
    'no_workouts_history': 'No workouts yet',
    'start_training_msg': 'Start training to see your history here.',
    'quick_start': 'Quick Start',

    // Gamification
    'achievements_title': 'Achievements',
    'monthly_challenges': 'Monthly Challenges',
    'step_master': 'Step Master',
    'reach_steps_goal': 'Reach 180k steps',
    'calorie_burn': 'Calorie Burn',
    'goal_label': 'Goal:',
    'distance_label': 'Distance',
    'badges_section': 'Badges',

    // Badge Details
    'badge_name_first_step': 'First Step',
    'badge_desc_first_step': 'Complete your first workout',
    'badge_name_getting_serious': 'Getting Serious',
    'badge_desc_getting_serious': 'Complete 10 workouts',
    'badge_name_gym_rat': 'Gym Rat',
    'badge_desc_gym_rat': 'Complete 50 workouts',
    'badge_name_warming_up': 'Warming Up',
    'badge_desc_warming_up': 'Reach a 3-day streak',
    'badge_name_unstoppable': 'Unstoppable',
    'badge_desc_unstoppable': 'Reach a 7-day streak',
    'badge_name_social_butterfly': 'Social Butterfly',
    'badge_desc_social_butterfly': 'Connect with a friend',

    // Set editor (US-046)
    'set_label': 'Set',
    'previous_set': 'Previous set',
    'load_label': 'Load',
    'reps_label': 'Reps',
    'rpe_full_label': 'Perceived effort',
    'close_set': 'Close the set',

    // Missing strings found on screen: `t` returns the key when it is absent,
    // so these were being displayed as `rpe_label`, `cancel`, and so on.
    'cancel': 'Cancel',
    'login_required': 'Sign in to continue',
    'completed_at': 'Completed at',
    'scheduled_for': 'Scheduled for',
    'friend_label': '(friend)',
    'event_deleted': 'Event deleted',
    'no_workouts_create_first': 'No workouts yet. Create one first!',
    'error_connecting': 'Error while connecting',
    'error_deleting': 'Error while deleting',
    'gymflow_user': 'GymFlow user',
    'rpe_label': 'Avg Effort',

    // Exercises
    'exercises_menu': 'Exercises',
    'exercises_title': 'Exercise library',
    'exercises_search': 'Search exercise',
    'exercises_search_placeholder': 'Search among your exercises',
    'exercises_empty': 'No exercises yet. Load the curated library from Settings, or add your own.',
    'exercises_recent_empty': 'No history yet',
    'exercises_no_match': 'No exercise matches these filters.',
    'exercises_new_btn': 'New exercise',
    'exercise_filter_all': 'All',
    'exercise_filter_mine': 'Mine',
    'exercise_filter_recent': 'Recent',
    'exercise_tag_yours': 'yours',
    'exercise_tag_no_video': 'no video',
    'video_available': 'Execution video available',
    'add_exercise_title': 'New Custom Exercise',
    'add_exercise_name_label': 'Exercise Name',
    'add_exercise_name_empty': 'Please enter an exercise name',
    'add_exercise_error_saving': 'Error saving exercise',

    // Execution video
    'video_none': 'No execution video for this exercise yet.',
    'video_search_only':
        'No specific video has been picked for this exercise yet. You can search for it on YouTube.',
    'video_open_search': 'Search on YouTube',
    'video_unavailable':
        'This video is no longer available, or its author does not allow it to be played here.',
    'video_offline':
        'Watching the video needs a connection. Check your network and try again.',
    'video_open_failed': 'Could not open YouTube',

    // Workout summary & receipt
    'workout_summary_title': 'Workout Summary',
    'workout_summary_completed_pill': 'Workout completed',
    'workout_summary_close_cta': 'Close',
    'workout_untitled': 'Workout',
    'workout_receipt_header': 'WORKOUT',
    'workout_receipt_volume': 'Volume lifted',
    'workout_receipt_completed_sets': 'Completed sets',
    'workout_receipt_avg_rpe': 'Average effort',
    'workout_receipt_calories': 'Calories',
    'workout_receipt_avg_heart_rate': 'Average heart rate',

    // Live metrics (US-047)
    'live_metrics_calories': 'CALORIES',
    'live_metrics_heart_rate': 'HEART RATE',
    'live_metrics_permission_prompt':
        'Enable Health to see live calories and heart rate.',
    'live_metrics_grant_permission': 'Enable Health',

    // US-100: la sintesi salute delle statistiche. Non riusa le chiavi del
    // pannello dal vivo: quelle parlano di calorie e battito, qui si tratta di
    // passi e calorie, e un messaggio che nomina la cosa sbagliata e peggio di
    // un messaggio generico.
    'health_permission_needed': 'GymFlow cannot read your health data.',
    'health_permission_missing_prefix': 'Missing permission for:',
    'health_permission_grant': 'Allow reading',
    'live_metrics_in_progress': 'In progress',
    'live_metrics_kcal': 'kcal',
    'live_metrics_bpm': 'bpm',

    // Personal records (US-050)
    'record_pill': 'Record',
    'record_over_max': 'over your max',
    'previous_max_was': 'Previous max was',
    'on_date': 'on',

    // Main screens & Active Session (US-026)
    'athlete': 'Athlete',
    'welcome_back': 'Welcome back,',
    'start_workout': 'Start Workout',
    'no_programs_found': 'No programs found. Create one first!',
    'exercises_suffix': 'Exercises',
    'gym_label': 'Gym',
    'weights_loaded_msg': 'Weights loaded from last session!',
    'finish_workout_title': 'Finish Workout',
    'finish_workout_body': 'Great job! Save this workout?',
    'date_label': 'Date',
    'save': 'Save',
    'confirm_date': 'CONFIRM DATE',
    'confirm_end_time': 'CONFIRM END TIME',
    'finish_btn': 'FINISH',
    'remove_exercise_title': 'Remove Exercise?',
    'remove_exercise_body':
        'Remove this exercise from the current session?',
    'remove_btn': 'Remove',
    'add_set': 'Add Set',
    'time_min_label': 'Time (min)',
    'duration_sec_label': 'Duration (sec)',
    'timer_started_msg': 'Timer started',

    // Exercise detail & progression (US-068)
    'exercise_detail_title': 'Exercise Details',
    'exercise_progression_title': 'Weight progression',
    'exercise_period_1m': '1 Month',
    'exercise_period_3m': '3 Months',
    'exercise_period_all': 'All',
    'exercise_personal_best_title': 'Personal Best',
    'exercise_no_history_title': 'No history yet',
    'exercise_no_history_body': 'Perform this exercise in a workout to track your progression over time.',
    'exercise_last_session_title': 'Last Session',
    'exercise_set_label': 'Set',
    'exercise_completed_label': 'Completed',
    'exercise_not_completed_label': 'Not completed',
    // Body measurements (US-066)
    'current_weight': 'Current weight',
    'weight_history': 'Weight history',
    'body_measures_section': 'Body measures',
    'bm_weight': 'Weight',
    'bm_waist': 'Waist',
    'bm_hips': 'Hips',
    'bm_arms': 'Arms',
    'bm_height': 'Height',
    'bm_chest': 'Chest',
    'bm_thighs': 'Thighs',
    'bm_calves': 'Calves',
    'bm_shoulders': 'Shoulders',
    'bm_neck': 'Neck',
    'bm_body_fat': 'Body fat',
    'bm_percent': '%',
    'bm_kg': 'kg',
    'bm_cm': 'cm',
    'enter_weight': 'Enter weight',
    'measurements_saved': 'Measurements saved',
    'no_measurements': 'No measurements yet',
    'home_in_progress': 'In progress',
    'home_day_of': 'Day %s / %s',
    'home_resume_workout': 'Resume workout',
    'home_no_active_program': 'No active program',
    'home_create_program_prompt': 'Create a workout program to get started.',
    'home_create_program_action': 'Create program',
    'home_today_in_workout': 'Today in workout',
    'home_min': 'min',
    'home_exercises': 'exercises',
    'home_exercise_one': 'exercise',
    'finish_now': 'Finish now',
    'finish_other_date': 'Another date',
    'exercise_done': 'Exercise completed',
    'time_ready': 'Ready',
    'time_running': 'Running',
    'time_paused': 'Paused',
      'profile_tab': 'Profile',
    'calendar_tab': 'Calendar',
    'programs_tab': 'Programs',
    'import_program_tooltip': 'Import Program',
    'import_program_title': 'Import Program?',
    'cancel_caps': 'CANCEL',
    'import_caps': 'IMPORT',
    'program_imported_success': 'Program imported successfully!',
    'week_tab': 'Week',
    'month_tab': 'Month',
    'total_average': 'Total / Average',
    'no_data': 'No Data',
    'health_total_hours': 'Total: %s h',
    'activity_heatmap_tooltip': '%s: %s workouts',
    'reset_password': 'Reset Password',
    'email_label': 'Email',
    'invalid_email': 'Enter a valid email',
    'password_reset_sent': 'Password reset email sent',
    'send_btn': 'Send',
    'password_too_short': 'Password too short',
    'forgot_password': 'Forgot Password?',
    'profile_updated': 'Profile updated',
    'username_label': 'Username',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'gender_label': 'Gender',
    'select_date_label': 'Select Date',
    'gender_female': 'Female',
    'gender_other': 'Other',
    'birth_date_label': 'Birth Date',
    'program_saved_success': 'Program saved successfully!',
    'program_name': 'Program Name',
    'program_name_hint': 'e.g. Winter Bulk, Summer Shred',
    'name_required': 'Name required',
    'description_label': 'Description',
    'description_hint': 'Goals, focus, notes...',
    'tap_to_select_dates': 'Tap to select dates',
    'add_workout_day': 'Add Workout Day',
    'create_account': 'Create Account',
    'full_name': 'Full Name',
    'password_label': 'Password',
    'password_too_short_min6': 'Password too short (min 6)',
    'gym_name_label': 'Gym Name',
    'address_label': 'Address',
    'update_info_btn': 'Update Info',
    'tap_to_select_location': 'Tap to select location',
    'user_not_authenticated': 'User not authenticated',
    'add_at_least_one_exercise': 'Add at least one exercise',
    'add_btn': 'Add',
    'gender_male': 'Male',
    'error_prefix': 'Error',
    'login_btn': 'LOGIN',
    'no_account_signup': "Don't have an account? Sign Up",
    'signup_btn': 'SIGN UP',
    'basic_info': 'Basic Info',
    'color_label': 'Color',
    'duration_section': 'Duration',
    'no_days_added': 'No days added yet',
    'notes_optional': 'Notes / Cue (Optional)',
    'day_name_hint': 'Day Name (e.g. Push Day)',
    'no_history_shared': 'No workout history shared.',
    'no_programs_shared': 'No programs shared.',
    'friend_no_shared_content': "%s hasn't shared any content yet.",
    'error_loading_programs': 'Error loading programs',

    // Il secondo giro di US-027: le stringhe che il primo test non vedeva
    // perche stavano sulla riga sotto `Text(` o dentro un widget interno.
    'login_welcome_back': 'Welcome Back',
    'reset_password_hint':
        'Enter your email address to receive a password reset link.',
    'join_gymflow': 'Join GymFlow',
    'upload_failed': 'Upload failed',
    'image_url_failed': 'Failed to get image URL',
    'profile_save_failed': 'Failed to save profile',
    'program_save_error': 'Error saving program',
    'new_program': 'New Program',
    'edit_program': 'Edit Program',
    'date_range_label': 'Start - End Date',
    'save_program_first': 'Save program to add workout days.',
    'focus_category': 'Focus Category',
    'configure_cardio': 'Configure Cardio',
    'configure_strength': 'Configure Strength',
    'new_exercise': 'New Exercise',
    'distance_km_label': 'Distance (km)',
    'sets_label': 'Sets',
    'weight_kg_label': 'Weight (kg)',
    'rest_sec_label': 'Rest (sec)',
    'rest_label': 'Rest',
    'note_label': 'Note',
    'save_exercise': 'Save Exercise',
    'new_day': 'New Day',
    'edit_day': 'Edit Day',
    'exercises_section': 'Exercises',
    'no_exercises_added': 'No exercises added yet',
    'subscription_active': 'ACTIVE',
    'subscription_expired': 'EXPIRED',
    'default_user_name': 'User',
    'info_save_error': 'Error saving info',
    // %s e il nome della scheda: stessa forma di `home_day_of`, che e la sola
    // convenzione per i segnaposto che questo dizionario abbia.
    'import_program_confirm':
        'Do you want to add "%s" to your library? This will create a copy of '
        'the program and all its workouts.',
    'import_failed': 'Failed to import',
    'statistics_title': 'Statistics',
    'statistics_tab': 'Statistics',
  };

  static final Map<String, String> _it = {
    'settings_title': 'Impostazioni',
    'account_section': 'ACCOUNT',
    'my_profile': 'Il Mio Profilo',
    'body_measurements': 'Misure Corporee',
    'subscription': 'Abbonamento',
    'gym_settings_section': 'IMPOSTAZIONI PALESTRA',
    'gym_details': 'Dettagli Palestra',
    'gym_location': 'Posizione Palestra',
    'integrations_section': 'INTEGRAZIONI',
    'preferences_section': 'PREFERENZE',
    'notifications': 'Notifiche',
    'app_theme': 'Tema App',
    'language': 'Lingua',
    'primary_color': 'Colore Principale',
    'load_default_data': 'Carica Dati Default',
    'sign_out': 'Esci',
    'guest_user': 'Utente Ospite',
    'track_progress': 'Traccia i tuoi progressi',
    'free_plan': 'Piano Gratuito',
    'expires': 'Scade il',
    'set_name_address': 'Imposta Nome e Indirizzo',
    'location_pinned': 'Posizione salvata',
    'tap_to_set': 'Tocca per impostare',
    'sync_steps': 'Sincronizza passi, calorie, etc.',
    'permissions_granted': 'Permessi concessi!',
    'default_loaded': 'Esercizi caricati!',
    'gym_info_saved': 'Info Palestra Salvate!',
    'system': 'Sistema',
    'light': 'Chiaro',
    'dark': 'Scuro',
    'select_language': 'Seleziona Lingua',
    'home': 'Home',
    'achievements': 'Obiettivi',
    'stopwatch_menu': 'Cronometro',
    'connect_friend': 'Connetti Amico',
    'stopwatch_tab': 'Cronometro',
    'timer_tab': 'Timer',
    'lap': 'Parziale',
    'reset': 'Azzera',
    'pause': 'Pausa',
    'start': 'Avvia',
    'tap_to_edit': 'Tocca per modificare',

    // Calendar
    'calendar_title': 'Calendario',
    'select_day': 'Seleziona un giorno',
    'no_workouts_day': 'Nessun allenamento',
    'schedule_workout': 'Programma Allenamento',
    'schedule_workout_btn': 'Programma Allenamento',
    'delete_event_title': 'Elimina Evento?',
    'delete_event_body': 'Questa azione non può essere annullata.',
    'sync_calendar': 'Sincronizza con Calendario',
    'workout_label': 'Allenamento:',
    'scheduled_using': 'Programmato con GymFlow',
    'select_workout_schedule': 'Seleziona Allenamento da Programmare',
    'no_workouts_found': 'Nessun allenamento trovato. Creane uno prima!',

    // Connect Friend
    'connect_friends_title': 'Connetti Amici',
    'your_friend_code': 'Il tuo Codice Amico',
    'share_code_msg':
        'Condividi questo codice con i tuoi amici per farti aggiungere!',
    'enter_friend_code': 'Inserisci Codice Amico',
    'friend_code_hint': 'es. A1B2C3',
    'connect_btn': 'CONNETTI',
    'your_friends_list': 'I tuoi Amici',
    'no_friends_msg': 'Ancora nessun amico. Aggiungine qualcuno!',
    'privacy_settings': 'Privacy:',
    'share_calendar': 'Condividi Calendario',
    'share_calendar_sub': 'Permetti di vedere la tua cronologia',
    'share_programs': 'Condividi Schede',
    'share_programs_sub': 'Permetti di vedere/copiare le tue schede',
    'done': 'FATTO',
    'cant_add_self': 'Non puoi aggiungere te stesso!',
    'friend_connected': 'Amico connesso con successo!',
    'friend_not_found': 'Amico non trovato con codice:',

    // Program List
    'my_programs_title': 'Le mie Schede',
    'no_programs_yet': 'Nessuna Scheda',
    'create_program_msg': 'Crea una scheda di allenamento per iniziare',
    'delete': 'Elimina',
    'delete_program_title': 'Elimina Scheda?',
    'delete_program_body_prefix': 'Sei sicuro di voler eliminare',
    'program_deleted': 'Scheda eliminata',
    'active_caps': 'ATTIVA',
    'ongoing': 'In corso',
    'no_dates': 'Nessuna data',
    'days_label': 'Giorni',

    // Dashboard
    'dashboard_title': 'Dashboard',
    'overview_tab': 'Panoramica',
    'history_tab': 'Storico',
    'workouts_label': 'Allenamenti',
    'streak_label': 'Streak',
    'steps_label': 'Passi',
    'active_cal_label': 'Calorie Attive',
    'heart_rate_label': 'Battito Card.',
    'sleep_label': 'Sonno',
    'volume_label': 'Volume',
    'avg_intensity_label': 'IntensitÃ  Media',
    'my_gym_label': 'La mia Palestra',
    'workout_activity_chart': 'AttivitÃ  Allenamento',
    'body_progress_chart': 'Progresso Corporeo',
    'workout_types_chart': 'Tipi di Allenamento',
    'workout_type_strength': 'Forza',
    'workout_type_cardio': 'Cardio',
    'workout_type_hypertrophy': 'Ipertrofia',
    'workout_type_flexibility': 'Flessibilità',
    'no_workouts_history': 'Nessun allenamento ancora',
    'start_training_msg': 'Inizia ad allenarti per vedere il tuo storico qui.',
    'quick_start': 'Avvio Rapido',

    // Gamification
    'achievements_title': 'Obiettivi',
    'monthly_challenges': 'Sfide Mensili',
    'step_master': 'Signore dei Passi',
    'reach_steps_goal': 'Raggiungi 180k passi',
    'calorie_burn': 'Calorie Bruciate',
    'goal_label': 'Obiettivo:',
    'distance_label': 'Distanza',
    'badges_section': 'Badge',

    // Badge Details
    'badge_name_first_step': 'Primo Passo',
    'badge_desc_first_step': 'Completa il tuo primo allenamento',
    'badge_name_getting_serious': 'Si fa sul serio',
    'badge_desc_getting_serious': 'Completa 10 allenamenti',
    'badge_name_gym_rat': 'Topo da Palestra',
    'badge_desc_gym_rat': 'Completa 50 allenamenti',
    'badge_name_warming_up': 'Riscaldamento',
    'badge_desc_warming_up': 'Raggiungi una serie di 3 giorni',
    'badge_name_unstoppable': 'Inarrestabile',
    'badge_desc_unstoppable': 'Raggiungi una serie di 7 giorni',
    'badge_name_social_butterfly': 'Animale Sociale',
    'badge_desc_social_butterfly': 'Connettiti con un amico',

    // Editor della serie (US-046)
    'set_label': 'Serie',
    'previous_set': 'Serie precedente',
    'load_label': 'Carico',
    'reps_label': 'Ripetizioni',
    'rpe_full_label': 'Sforzo percepito',
    'close_set': 'Chiudi la serie',

    // Stringhe mancanti trovate a schermo: `t` restituisce la chiave quando
    // manca, quindi al loro posto si leggeva `rpe_label`, `cancel`, e cosi via.
    'cancel': 'Annulla',
    'login_required': 'Accedi per continuare',
    'completed_at': 'Completato alle',
    'scheduled_for': 'Programmato per le',
    'friend_label': '(amico)',
    'event_deleted': 'Evento eliminato',
    'no_workouts_create_first': 'Nessun allenamento. Creane uno prima!',
    'error_connecting': 'Errore durante la connessione',
    'error_deleting': "Errore durante l'eliminazione",
    'gymflow_user': 'Utente GymFlow',
    // Il valore che accompagna viene da calculateAverageRPE: e lo sforzo
    // percepito, non l'intensita, che e gia un'altra voce.
    'rpe_label': 'Sforzo medio',

    // Esercizi
    'exercises_menu': 'Esercizi',
    'exercises_title': 'Libreria esercizi',
    'exercises_search': 'Cerca esercizio',
    'exercises_search_placeholder': 'Cerca fra i tuoi esercizi',
    'exercises_empty': 'Nessun esercizio. Carica la libreria dalle impostazioni, oppure creane uno tuo.',
    'exercises_recent_empty': 'Ancora nessuno storico',
    'exercises_no_match': 'Nessun esercizio corrisponde a questi filtri.',
    'exercises_new_btn': 'Nuovo esercizio',
    'exercise_filter_all': 'Tutti',
    'exercise_filter_mine': 'Miei',
    'exercise_filter_recent': 'Recenti',
    'exercise_tag_yours': 'tuo',
    'exercise_tag_no_video': 'senza video',
    'video_available': "Video dell'esecuzione disponibile",
    'add_exercise_title': 'Nuovo esercizio personalizzato',
    'add_exercise_name_label': 'Nome esercizio',
    'add_exercise_name_empty': "Inserisci un nome per l'esercizio",
    'add_exercise_error_saving': "Errore durante il salvataggio dell'esercizio",

    // Video dell'esecuzione
    'video_none': "Per questo esercizio non c'e ancora un video.",
    'video_search_only':
        "Per questo esercizio non e ancora stato scelto un video preciso. Puoi cercarlo su YouTube.",
    'video_open_search': 'Cerca su YouTube',
    'video_unavailable':
        "Questo video non e piu disponibile, oppure il suo autore non ne permette la visione qui.",
    'video_offline':
        'Per vedere il video serve una connessione. Controlla la rete e riprova.',
    'video_open_failed': 'Non e stato possibile aprire YouTube',

    // Workout summary & receipt
    'workout_summary_title': 'Riepilogo allenamento',
    'workout_summary_completed_pill': 'Allenamento chiuso',
    'workout_summary_close_cta': 'Chiudi',
    'workout_untitled': 'Allenamento',
    'workout_receipt_header': 'SCHEDA',
    'workout_receipt_volume': 'Volume sollevato',
    'workout_receipt_completed_sets': 'Serie completate',
    'workout_receipt_avg_rpe': 'Sforzo medio',
    'workout_receipt_calories': 'Calorie',
    'workout_receipt_avg_heart_rate': 'Battito medio',

    // Live metrics (US-047)
    'live_metrics_calories': 'CALORIE',
    'live_metrics_heart_rate': 'BATTITO',
    'live_metrics_permission_prompt':
        'Attiva Salute per vedere calorie e battito dal vivo.',
    'live_metrics_grant_permission': 'Attiva Salute',

    // US-100: la sintesi salute delle statistiche. Non riusa le chiavi del
    // pannello dal vivo: quelle parlano di calorie e battito, qui si tratta di
    // passi e calorie, e un messaggio che nomina la cosa sbagliata e peggio di
    // un messaggio generico.
    'health_permission_needed': 'GymFlow non riesce a leggere i tuoi dati di salute.',
    'health_permission_missing_prefix': 'Manca il permesso per:',
    'health_permission_grant': 'Consenti la lettura',
    'live_metrics_in_progress': 'In corso',
    'live_metrics_kcal': 'kcal',
    'live_metrics_bpm': 'bpm',

    // Record personali (US-050)
    'record_pill': 'Record',
    'record_over_max': 'sul tuo massimo',
    'previous_max_was': 'Il massimo precedente era',
    'on_date': 'il',

    // Main screens & Active Session (US-026)
    'athlete': 'Atleta',
    'welcome_back': 'Bentornato,',
    'start_workout': 'Avvia allenamento',
    'no_programs_found': 'Nessuna scheda trovata. Creane una prima!',
    'exercises_suffix': 'Esercizi',
    'gym_label': 'Palestra',
    'weights_loaded_msg': 'Pesi caricati dall\'ultimo allenamento!',
    'finish_workout_title': 'Termina Allenamento',
    'finish_workout_body': 'Ottimo lavoro! Salvare questo allenamento?',
    'date_label': 'Data',
    'save': 'Salva',
    'confirm_date': 'CONFERMA DATA',
    'confirm_end_time': 'CONFERMA ORA DI FINE',
    'finish_btn': 'TERMINA',
    'remove_exercise_title': 'Rimuovere l\'esercizio?',
    'remove_exercise_body':
        'Rimuovere questo esercizio dalla sessione corrente?',
    'remove_btn': 'Rimuovi',
    'add_set': 'Aggiungi serie',
    'time_min_label': 'Tempo (min)',
    'duration_sec_label': 'Durata (sec)',
    'timer_started_msg': 'Timer avviato',

    // Exercise detail & progression (US-068)
    'exercise_detail_title': 'Dettagli esercizio',
    'exercise_progression_title': 'Progressione carico',
    'exercise_period_1m': '1 Mese',
    'exercise_period_3m': '3 Mesi',
    'exercise_period_all': 'Tutto',
    'exercise_personal_best_title': 'Record Personale',
    'exercise_no_history_title': 'Ancora nessuno storico',
    'exercise_no_history_body': 'Esegui questo esercizio in un allenamento per tracciare la tua progressione nel tempo.',
    'exercise_last_session_title': 'Ultima sessione',
    'exercise_set_label': 'Serie',
    'exercise_completed_label': 'Completata',
    'exercise_not_completed_label': 'Non completata',
    // Peso e misure (US-066)
    'current_weight': 'Peso attuale',
    'weight_history': 'Storico pesi',
    'body_measures_section': 'Misure corporee',
    'bm_weight': 'Peso',
    'bm_waist': 'Vita',
    'bm_hips': 'Fianchi',
    'bm_arms': 'Braccia',
    'bm_height': 'Altezza',
    'bm_chest': 'Petto',
    'bm_thighs': 'Cosce',
    'bm_calves': 'Polpacci',
    'bm_shoulders': 'Spalle',
    'bm_neck': 'Collo',
    'bm_body_fat': 'Massa grassa',
    'bm_percent': '%',
    'bm_kg': 'kg',
    'bm_cm': 'cm',
    'enter_weight': 'Inserisci peso',
    'measurements_saved': 'Misurazioni salvate',
    'no_measurements': 'Nessuna misurazione',
    'home_in_progress': 'In corso',
    'home_day_of': 'Giorno %s / %s',
    'home_resume_workout': 'Riprendi l\'allenamento',
    'home_no_active_program': 'Nessuna scheda attiva',
    'home_create_program_prompt': 'Crea una scheda di allenamento per iniziare.',
    'home_create_program_action': 'Crea scheda',
    'home_today_in_workout': 'Oggi in scheda',
    'home_min': 'min',
    'home_exercises': 'esercizi',
    'home_exercise_one': 'esercizio',
    'finish_now': 'Termina adesso',
    'finish_other_date': 'Altra data',
    'exercise_done': 'Esercizio completato',
    'time_ready': 'Pronto',
    'time_running': 'In corso',
    'time_paused': 'In pausa',
      'profile_tab': 'Profilo',
    'calendar_tab': 'Calendario',
    'programs_tab': 'Programmi',
    'import_program_tooltip': 'Importa Programma',
    'import_program_title': 'Importare Programma?',
    'cancel_caps': 'ANNULLA',
    'import_caps': 'IMPORTA',
    'program_imported_success': 'Programma importato con successo!',
    'week_tab': 'Settimana',
    'month_tab': 'Mese',
    'total_average': 'Totale / Media',
    'no_data': 'Nessun Dato',
    'health_total_hours': 'Totale: %s h',
    'activity_heatmap_tooltip': '%s: %s allenamenti',
    'reset_password': 'Reset Password',
    'email_label': 'Email',
    'invalid_email': 'Inserisci unemail valida',
    'password_reset_sent': 'Email di reset password inviata',
    'send_btn': 'Invia',
    'password_too_short': 'Password troppo corta',
    'forgot_password': 'Password dimenticata?',
    'profile_updated': 'Profilo aggiornato',
    'username_label': 'Nome utente',
    'first_name': 'Nome',
    'last_name': 'Cognome',
    'gender_label': 'Sesso',
    'select_date_label': 'Seleziona Data',
    'gender_female': 'Donna',
    'gender_other': 'Altro',
    'birth_date_label': 'Data di Nascita',
    'program_saved_success': 'Programma salvato con successo!',
    'program_name': 'Nome Programma',
    'program_name_hint': 'es. Massa Invernale, Definizione Estiva',
    'name_required': 'Il nome è richiesto',
    'description_label': 'Descrizione',
    'description_hint': 'Obiettivi, focus, note...',
    'tap_to_select_dates': 'Tocca per selezionare le date',
    'add_workout_day': 'Aggiungi Giorno di Allenamento',
    'create_account': 'Crea Account',
    'full_name': 'Nome Completo',
    'password_label': 'Password',
    'password_too_short_min6': 'Password troppo corta (min 6)',
    'gym_name_label': 'Nome Palestra',
    'address_label': 'Indirizzo',
    'update_info_btn': 'Aggiorna Info',
    'tap_to_select_location': 'Tocca per selezionare la posizione',
    'user_not_authenticated': 'Utente non autenticato',
    'add_at_least_one_exercise': 'Aggiungi almeno un esercizio',
    'add_btn': 'Aggiungi',
    'gender_male': 'Uomo',
    'error_prefix': 'Errore',
    'login_btn': 'ACCEDI',
    'no_account_signup': 'Non hai un account? Registrati',
    'signup_btn': 'REGISTRATI',
    'basic_info': 'Info di base',
    'color_label': 'Colore',
    'duration_section': 'Durata',
    'no_days_added': 'Nessun giorno aggiunto',
    'notes_optional': 'Note / Spunti (Opzionale)',
    'day_name_hint': 'Nome Giorno (es. Spinta)',
    'no_history_shared': 'Nessuno storico condiviso.',
    'no_programs_shared': 'Nessuna scheda condivisa.',
    'friend_no_shared_content': '%s non ha ancora condiviso nulla.',
    'error_loading_programs': 'Errore caricamento schede',

    // Il secondo giro di US-027: le stringhe che il primo test non vedeva
    // perche stavano sulla riga sotto `Text(` o dentro un widget interno.
    'login_welcome_back': 'Bentornato',
    'reset_password_hint':
        'Inserisci il tuo indirizzo email per ricevere il link di reimpostazione.',
    'join_gymflow': 'Unisciti a GymFlow',
    'upload_failed': 'Caricamento non riuscito',
    'image_url_failed': "Impossibile ottenere l'indirizzo dell'immagine",
    'profile_save_failed': 'Salvataggio del profilo non riuscito',
    'program_save_error': 'Errore nel salvataggio della scheda',
    'new_program': 'Nuova scheda',
    'edit_program': 'Modifica scheda',
    'date_range_label': 'Data di inizio - fine',
    'save_program_first': 'Salva la scheda per aggiungere i giorni.',
    'focus_category': 'Categoria principale',
    'configure_cardio': 'Configura cardio',
    'configure_strength': 'Configura pesi',
    'new_exercise': 'Nuovo esercizio',
    'distance_km_label': 'Distanza (km)',
    'sets_label': 'Serie',
    'weight_kg_label': 'Peso (kg)',
    'rest_sec_label': 'Recupero (sec)',
    'rest_label': 'Recupero',
    'note_label': 'Nota',
    'save_exercise': 'Salva esercizio',
    'new_day': 'Nuovo giorno',
    'edit_day': 'Modifica giorno',
    'exercises_section': 'Esercizi',
    'no_exercises_added': 'Nessun esercizio aggiunto',
    'subscription_active': 'ATTIVO',
    'subscription_expired': 'SCADUTO',
    'default_user_name': 'Utente',
    'info_save_error': 'Errore nel salvataggio dei dati',
    // %s e il nome della scheda: stessa forma di `home_day_of`, che e la sola
    // convenzione per i segnaposto che questo dizionario abbia.
    'import_program_confirm':
        'Vuoi aggiungere "%s" alla tua libreria? Ne verra creata una copia con '
        'tutti i suoi allenamenti.',
    'import_failed': 'Importazione non riuscita',
    'statistics_title': 'Statistiche',
    'statistics_tab': 'Statistiche',
  };
}

/// Espone la lingua corrente e le sue traduzioni, persistendo la scelta.
///
/// Come per il tema, [build] restituisce subito il default e avvia la lettura
/// da `SharedPreferences`: nessuno stato di caricamento da gestire nella UI.
@Riverpod(keepAlive: true)
class LocalizationNotifier extends _$LocalizationNotifier {
  static const _languageKey = 'language_code';
  static const _defaultLocale = Locale('it');

  @override
  Localization build() {
    _restore();
    return const Localization(_defaultLocale);
  }

  Future<void> _restore() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString(_languageKey);
    if (savedCode != null && savedCode.isNotEmpty) {
      state = Localization(Locale(savedCode));
    }
  }

  Future<void> setLocale(Locale locale) async {
    state = Localization(locale);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, locale.languageCode);
  }
}
