// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC64r2zGe0U1PF0izMbdkknPHw416xi3fk',
    appId: '1:704225438245:web:cce7285b0116d71811adcc',
    messagingSenderId: '704225438245',
    projectId: 'gymflow-d5d09',
    authDomain: 'gymflow-d5d09.firebaseapp.com',
    storageBucket: 'gymflow-d5d09.firebasestorage.app',
    measurementId: 'G-3368CKE0VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArwyfsWmVQg6HxsymQ87alxLENMxKcQ0w',
    appId: '1:704225438245:android:6f9ef9d23956b23e11adcc',
    messagingSenderId: '704225438245',
    projectId: 'gymflow-d5d09',
    storageBucket: 'gymflow-d5d09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOVza1p0EgwA8oundGYIjijJtNPI3cM4k',
    appId: '1:704225438245:ios:c6c610c075b5932811adcc',
    messagingSenderId: '704225438245',
    projectId: 'gymflow-d5d09',
    storageBucket: 'gymflow-d5d09.firebasestorage.app',
    iosBundleId: 'com.example.gymflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOVza1p0EgwA8oundGYIjijJtNPI3cM4k',
    appId: '1:704225438245:ios:c6c610c075b5932811adcc',
    messagingSenderId: '704225438245',
    projectId: 'gymflow-d5d09',
    storageBucket: 'gymflow-d5d09.firebasestorage.app',
    iosBundleId: 'com.example.gymflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC64r2zGe0U1PF0izMbdkknPHw416xi3fk',
    appId: '1:704225438245:web:f1ce3155bd8c80a011adcc',
    messagingSenderId: '704225438245',
    projectId: 'gymflow-d5d09',
    authDomain: 'gymflow-d5d09.firebaseapp.com',
    storageBucket: 'gymflow-d5d09.firebasestorage.app',
    measurementId: 'G-2SC616KV21',
  );
}
